spring:
  application:
    name: java-board
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true
    properties:
      hibernate:
        format_sql: true # 쿼리를 한 줄 말고 예쁘게 줄바꿈해서 출력
        highlight_sql: true # 쿼리에 색상 입히기 (가독성 UP)
